apiVersion: v1
kind: Service
metadata:
  name: {{ include "nivesh.fullname" . }}-backend-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nivesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "nivesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
